<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Teams extends \App\Entity\Teams implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'division' => [parent::class, 'division', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'percentage' => [parent::class, 'percentage', null],
        "\0".parent::class."\0".'points' => [parent::class, 'points', null],
        "\0".parent::class."\0".'torneo' => [parent::class, 'torneo', null],
        'division' => [parent::class, 'division', null],
        'id' => [parent::class, 'id', null],
        'name' => [parent::class, 'name', null],
        'percentage' => [parent::class, 'percentage', null],
        'points' => [parent::class, 'points', null],
        'torneo' => [parent::class, 'torneo', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
