<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tournament extends \App\Entity\Tournament implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'end_day' => [parent::class, 'end_day', null],
        "\0".parent::class."\0".'hour' => [parent::class, 'hour', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null],
        "\0".parent::class."\0".'number_of_tables' => [parent::class, 'number_of_tables', null],
        "\0".parent::class."\0".'players' => [parent::class, 'players', null],
        "\0".parent::class."\0".'start_day' => [parent::class, 'start_day', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'tournament_type' => [parent::class, 'tournament_type', null],
        'end_day' => [parent::class, 'end_day', null],
        'hour' => [parent::class, 'hour', null],
        'id' => [parent::class, 'id', null],
        'location' => [parent::class, 'location', null],
        'number_of_tables' => [parent::class, 'number_of_tables', null],
        'players' => [parent::class, 'players', null],
        'start_day' => [parent::class, 'start_day', null],
        'status' => [parent::class, 'status', null],
        'tournament_type' => [parent::class, 'tournament_type', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
