<?php

namespace Container94d3jgP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDaysOffService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lefnR3M.App\Entity\DaysOff' shared service.
     *
     * @return \App\Entity\DaysOff
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lefnR3M": it needs an instance of "App\\Entity\\DaysOff" but this type has been excluded in "config/services.yaml".');
    }
}
