<?php

namespace Container94d3jgP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControlleruserRegistrationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IgJ51vJ.App\Controller\DashboardController::userRegistration()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IgJ51vJ.App\\Controller\\DashboardController::userRegistration()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tournamentRepository' => ['privates', 'App\\Repository\\TournamentRepository', 'getTournamentRepositoryService', true],
            'userProfile' => ['privates', 'App\\Repository\\UserProfileRepository', 'getUserProfileRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tournamentRegistrationRepository' => ['privates', 'App\\Repository\\TournamentRegistrationRepository', 'getTournamentRegistrationRepositoryService', true],
            'teamsRepository' => ['privates', 'App\\Repository\\TeamsRepository', 'getTeamsRepositoryService', true],
            'teamsNamesRepository' => ['privates', 'App\\Repository\\TeamsNamesRepository', 'getTeamsNamesRepositoryService', true],
        ], [
            'tournamentRepository' => 'App\\Repository\\TournamentRepository',
            'userProfile' => 'App\\Repository\\UserProfileRepository',
            'entityManager' => '?',
            'tournamentRegistrationRepository' => 'App\\Repository\\TournamentRegistrationRepository',
            'teamsRepository' => 'App\\Repository\\TeamsRepository',
            'teamsNamesRepository' => 'App\\Repository\\TeamsNamesRepository',
        ]))->withContext('App\\Controller\\DashboardController::userRegistration()', $container);
    }
}
