<?php

namespace Container94d3jgP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerdashboardTournamentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dFQaI5D.App\Controller\DashboardController::dashboardTournament()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dFQaI5D.App\\Controller\\DashboardController::dashboardTournament()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'userProfileRepository' => ['privates', 'App\\Repository\\UserProfileRepository', 'getUserProfileRepositoryService', true],
            'tournamentRepository' => ['privates', 'App\\Repository\\TournamentRepository', 'getTournamentRepositoryService', true],
            'tournamentRegistration' => ['privates', 'App\\Repository\\TournamentRegistrationRepository', 'getTournamentRegistrationRepositoryService', true],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'userProfileRepository' => 'App\\Repository\\UserProfileRepository',
            'tournamentRepository' => 'App\\Repository\\TournamentRepository',
            'tournamentRegistration' => 'App\\Repository\\TournamentRegistrationRepository',
        ]))->withContext('App\\Controller\\DashboardController::dashboardTournament()', $container);
    }
}
