<?php

namespace Container94d3jgP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFollowerControllerunfollowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iPO2Ef7.App\Controller\FollowerController::unfollow()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iPO2Ef7.App\\Controller\\FollowerController::unfollow()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userToUnfollow' => ['privates', '.errored..service_locator.iPO2Ef7.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.iPO2Ef7": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'userToUnfollow' => 'App\\Entity\\User',
            'doctrine' => '?',
        ]))->withContext('App\\Controller\\FollowerController::unfollow()', $container);
    }
}
