<?php

namespace Container94d3jgP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHelloControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IivMof4.App\Controller\HelloController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IivMof4.App\\Controller\\HelloController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'posts' => ['privates', 'App\\Repository\\MicroPostRepository', 'getMicroPostRepositoryService', true],
            'comments' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'profiles' => ['privates', 'App\\Repository\\UserProfileRepository', 'getUserProfileRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'posts' => 'App\\Repository\\MicroPostRepository',
            'comments' => 'App\\Repository\\CommentRepository',
            'profiles' => 'App\\Repository\\UserProfileRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\HelloController::index()', $container);
    }
}
