<?php

namespace Container94d3jgP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProfileControllerprofileService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h59U8Hu.App\Controller\UserProfileController::profile()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h59U8Hu.App\\Controller\\UserProfileController::profile()'] = ($container->privates['.service_locator.h59U8Hu'] ?? $container->load('get_ServiceLocator_H59U8HuService'))->withContext('App\\Controller\\UserProfileController::profile()', $container);
    }
}
