<?php

namespace ContainerVlLAAWI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllercreateGamesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lefnR3M.App\Controller\DashboardController::createGames()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lefnR3M.App\\Controller\\DashboardController::createGames()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tournamentRepository' => ['privates', 'App\\Repository\\TournamentRepository', 'getTournamentRepositoryService', true],
            'userProfile' => ['privates', 'App\\Repository\\UserProfileRepository', 'getUserProfileRepositoryService', true],
            'tournamentRegistrationRepository' => ['privates', 'App\\Repository\\TournamentRegistrationRepository', 'getTournamentRegistrationRepositoryService', true],
            'daysOff' => ['privates', 'App\\Repository\\DaysOffRepository', 'getDaysOffRepositoryService', true],
            'daysOffEntity' => ['privates', '.errored..service_locator.lefnR3M.App\\Entity\\DaysOff', NULL, 'Cannot autowire service ".service_locator.lefnR3M": it needs an instance of "App\\Entity\\DaysOff" but this type has been excluded in "config/services.yaml".'],
            'tableEntity' => ['privates', '.errored..service_locator.lefnR3M.App\\Entity\\Table', NULL, 'Cannot autowire service ".service_locator.lefnR3M": it needs an instance of "App\\Entity\\Table" but this type has been excluded in "config/services.yaml".'],
            'tableRepository' => ['privates', 'App\\Repository\\TableRepository', 'getTableRepositoryService', true],
            'gamesRepository' => ['privates', 'App\\Repository\\GamesRepository', 'getGamesRepositoryService', true],
            'parametersRepository' => ['privates', 'App\\Repository\\ParametersRepository', 'getParametersRepositoryService', true],
        ], [
            'entityManager' => '?',
            'tournamentRepository' => 'App\\Repository\\TournamentRepository',
            'userProfile' => 'App\\Repository\\UserProfileRepository',
            'tournamentRegistrationRepository' => 'App\\Repository\\TournamentRegistrationRepository',
            'daysOff' => 'App\\Repository\\DaysOffRepository',
            'daysOffEntity' => 'App\\Entity\\DaysOff',
            'tableEntity' => 'App\\Entity\\Table',
            'tableRepository' => 'App\\Repository\\TableRepository',
            'gamesRepository' => 'App\\Repository\\GamesRepository',
            'parametersRepository' => 'App\\Repository\\ParametersRepository',
        ]))->withContext('App\\Controller\\DashboardController::createGames()', $container);
    }
}
