<?php

namespace ContainerVlLAAWI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardGamesControllercreateGameService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cbAUxKW.App\Controller\DashboardGamesController::createGame()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cbAUxKW.App\\Controller\\DashboardGamesController::createGame()'] = ($container->privates['.service_locator.cbAUxKW'] ?? $container->load('get_ServiceLocator_CbAUxKWService'))->withContext('App\\Controller\\DashboardGamesController::createGame()', $container);
    }
}
