<?php

namespace ContainerVlLAAWI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllereditUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DRgZUs0.App\Controller\DashboardController::editUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DRgZUs0.App\\Controller\\DashboardController::editUser()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userProfile' => ['privates', 'App\\Repository\\UserProfileRepository', 'getUserProfileRepositoryService', true],
        ], [
            'userPasswordHasher' => '?',
            'entityManager' => '?',
            'userProfile' => 'App\\Repository\\UserProfileRepository',
        ]))->withContext('App\\Controller\\DashboardController::editUser()', $container);
    }
}
