<?php

namespace ContainerVlLAAWI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerdashboardRegistrationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3lZyTsB.App\Controller\DashboardController::dashboardRegistration()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3lZyTsB.App\\Controller\\DashboardController::dashboardRegistration()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'userProfile' => ['privates', 'App\\Repository\\UserProfileRepository', 'getUserProfileRepositoryService', true],
            'tournamentRegistration' => ['privates', 'App\\Repository\\TournamentRegistrationRepository', 'getTournamentRegistrationRepositoryService', true],
            'teamsRepository' => ['privates', 'App\\Repository\\TeamsRepository', 'getTeamsRepositoryService', true],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'userProfile' => 'App\\Repository\\UserProfileRepository',
            'tournamentRegistration' => 'App\\Repository\\TournamentRegistrationRepository',
            'teamsRepository' => 'App\\Repository\\TeamsRepository',
        ]))->withContext('App\\Controller\\DashboardController::dashboardRegistration()', $container);
    }
}
