<?php

namespace ContainerVlLAAWI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLikeControllerlikeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.laJFieu.App\Controller\LikeController::like()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.laJFieu.App\\Controller\\LikeController::like()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'post' => ['privates', '.errored..service_locator.laJFieu.App\\Entity\\MicroPost', NULL, 'Cannot autowire service ".service_locator.laJFieu": it needs an instance of "App\\Entity\\MicroPost" but this type has been excluded in "config/services.yaml".'],
            'posts' => ['privates', 'App\\Repository\\MicroPostRepository', 'getMicroPostRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', true],
        ], [
            'post' => 'App\\Entity\\MicroPost',
            'posts' => 'App\\Repository\\MicroPostRepository',
            'entityManager' => '?',
            'logger' => '?',
        ]))->withContext('App\\Controller\\LikeController::like()', $container);
    }
}
