<?php

namespace ContainerVlLAAWI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMicroPostControlleraddCommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NFEiTKi.App\Controller\MicroPostController::addComment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NFEiTKi.App\\Controller\\MicroPostController::addComment()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'post' => ['privates', '.errored..service_locator.NFEiTKi.App\\Entity\\MicroPost', NULL, 'Cannot autowire service ".service_locator.NFEiTKi": it needs an instance of "App\\Entity\\MicroPost" but this type has been excluded in "config/services.yaml".'],
            'comments' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'post' => 'App\\Entity\\MicroPost',
            'comments' => 'App\\Repository\\CommentRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\MicroPostController::addComment()', $container);
    }
}
