<?php

namespace ContainerVlLAAWI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMicroPostControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RNgKSTQ.App\Controller\MicroPostController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RNgKSTQ.App\\Controller\\MicroPostController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'post' => ['privates', '.errored..service_locator.RNgKSTQ.App\\Entity\\MicroPost', NULL, 'Cannot autowire service ".service_locator.RNgKSTQ": it needs an instance of "App\\Entity\\MicroPost" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'post' => 'App\\Entity\\MicroPost',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\MicroPostController::edit()', $container);
    }
}
