<?php

namespace ContainerVlLAAWI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMicroPost5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.laJFieu.App\Entity\MicroPost' shared service.
     *
     * @return \App\Entity\MicroPost
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.laJFieu": it needs an instance of "App\\Entity\\MicroPost" but this type has been excluded in "config/services.yaml".');
    }
}
