<?php

namespace ContainerVlLAAWI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wExv4_0.App\Controller\ProfileController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wExv4_0.App\\Controller\\ProfileController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.wExv4_0.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.wExv4_0": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'posts' => ['privates', 'App\\Repository\\MicroPostRepository', 'getMicroPostRepositoryService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'posts' => 'App\\Repository\\MicroPostRepository',
        ]))->withContext('App\\Controller\\ProfileController::show()', $container);
    }
}
