<?php

namespace ContainerVlLAAWI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingsProfileControllerprofileImageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GjNmf51.App\Controller\SettingsProfileController::profileImage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.GjNmf51'] ?? $container->load('get_ServiceLocator_GjNmf51Service'));

        if (isset($container->privates['.service_locator.GjNmf51.App\\Controller\\SettingsProfileController::profileImage()'])) {
            return $container->privates['.service_locator.GjNmf51.App\\Controller\\SettingsProfileController::profileImage()'];
        }

        return $container->privates['.service_locator.GjNmf51.App\\Controller\\SettingsProfileController::profileImage()'] = $a->withContext('App\\Controller\\SettingsProfileController::profileImage()', $container);
    }
}
