<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container94d3jgP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container94d3jgP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container94d3jgP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container94d3jgP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container94d3jgP\App_KernelDevDebugContainer([
    'container.build_hash' => '94d3jgP',
    'container.build_id' => 'ab7e97ea',
    'container.build_time' => 1727952156,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container94d3jgP');
